export * from "@/pages/home";
export * from "@/pages/profile";
export * from "@/pages/aboutus";
export * from "@/pages/ourservices";
export * from "@/pages/ourusp";
export * from "@/pages/contactus";
export * from "@/pages/privacypolicy";
export * from "@/pages/sign-in";
export * from "@/pages/sign-up";
